#! /bin/bash
sudo setenforce 0
sudo yum clean all
sudo yum -y update
sudo yum -y install httpd
sudo systemctl start httpd
sudo systemctl enable httpd
sudo firewall-cmd --permanent --zone=public --add-service=http
sudo firewall-cmd --permanent --zone=public --add-service=https
sudo firewall-cmd --reload
sudo -s 
cat <<EOF > /var/www/html/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GONube Tecnologia</title>
</head>
<body>
    <center> <h1>Gonube Tecnologia - PRODUCAO AGORA !!!!</h1> 
            <h2>Instancia provisionada e Apache rodando com sucesso!!!! &#x270C; </h2>
            <h3>Viva o Oracle Linux!!!! &#x270C; </h3>
            <hr>
            <img src="https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/e28WG2oj7CDDKlHGiA4Op84o4dESPPorBE_zg2GutlZkQmsO_N1PRBigZWCUiwju/n/grtrwpdebm9u/b/BUCKET-TESTE-WEB/o/orl22ORL-Sup.png" alt="sucesso só com Oracle Linux">
    </center>    
</body>
</html>
EOF
